### ISSUE TITLE
Chamaeleon missing

### ISSUE THREAD

**Issue by nkrawler** [hemel-waarnemen-com/Constellation-lines#1]
I think it's the first Cam line, it's supposed to be Cha.
Thanks for the data

**Comment by MarcvdSluys** [comment]
I apologise for the slow response - I seem to have overlooked this issue - no impoliteness meant.  I only 'discovered' the issue while moving this repo to a different account - it sits here now: https://github.com/MarcvdSluys/ConstellationLines

You're absolutely right; this seems to be a 15- (meanwhile nearly 19-)year old typo.  Thanks for reporting, I'm going to fix this in the new repo.
